package analyzer

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// ArtifactHashAnalyzer verifies that a bundled skill script invoked by a
// command still matches the SHA-256 recorded for it in a declared-artifact
// manifest (generated by the comply scanner — schema-only integration). A
// mismatch means an unreviewed script is executing under a reviewed skill's
// trust: the runtime-attestation counterpart to the static skill-artifact
// inventory. See taxonomy
// supply-chain/artifact-integrity/skill-script-tampering.
//
// The feature is OFF unless AGENTSHIELD_ARTIFACT_MANIFEST names a loadable
// manifest — NewArtifactHashAnalyzer returns nil otherwise, so no pipeline
// stage exists and per-command cost is zero (mirrors the DataLabelAnalyzer
// conditional-append pattern). It is the first pipeline stage that reads the
// filesystem at eval time, so it is deliberately fail-safe: it emits a finding
// ONLY on a confirmed hash mismatch (the on-disk file is readable and its
// digest differs). Any uncertainty — an unreadable or missing file, a working
// directory that doesn't line up with the manifest — is silently skipped, so
// the feature can never produce a false BLOCK.
type ArtifactHashAnalyzer struct {
	// expected maps a manifest-declared, slash-normalized repo-relative script
	// path to its approved lowercase hex SHA-256.
	expected map[string]string
	// block is true when a confirmed mismatch should BLOCK; otherwise AUDIT.
	block bool
}

const (
	artifactRuleID      = "comply-skill-artifact-tamper"
	artifactTaxonomy    = "supply-chain/artifact-integrity/skill-script-tampering"
	envArtifactManifest = "AGENTSHIELD_ARTIFACT_MANIFEST"
	envArtifactMode     = "AGENTSHIELD_ARTIFACT_VERIFY_MODE" // "audit" (default) | "block"
)

// artifactManifest mirrors comply's emitted schema (schema-only contract —
// no shared Go code, matching the MCP-pack pattern).
type artifactManifest struct {
	Version   string `yaml:"version"`
	Artifacts []struct {
		Path   string `yaml:"path"`
		SHA256 string `yaml:"sha256"`
	} `yaml:"artifacts"`
}

// NewArtifactHashAnalyzer builds the analyzer from env config, or returns nil
// when the feature is not configured or the manifest can't be loaded. Returning
// nil (rather than an inert analyzer) keeps it out of the pipeline entirely.
func NewArtifactHashAnalyzer() *ArtifactHashAnalyzer {
	return newArtifactHashAnalyzerFromPath(
		os.Getenv(envArtifactManifest),
		strings.ToLower(strings.TrimSpace(os.Getenv(envArtifactMode))),
	)
}

func newArtifactHashAnalyzerFromPath(manifestPath, mode string) *ArtifactHashAnalyzer {
	if strings.TrimSpace(manifestPath) == "" {
		return nil
	}
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		// Feature requested but manifest unreadable: fail-safe to off rather
		// than blocking everything. (A stderr warning is emitted by the caller
		// context if desired; here we simply stay out of the pipeline.)
		return nil
	}
	var m artifactManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil
	}
	expected := make(map[string]string, len(m.Artifacts))
	for _, a := range m.Artifacts {
		p := strings.TrimPrefix(filepath.ToSlash(a.Path), "./")
		if p == "" || a.SHA256 == "" {
			continue
		}
		expected[p] = strings.ToLower(a.SHA256)
	}
	if len(expected) == 0 {
		return nil
	}
	return &ArtifactHashAnalyzer{expected: expected, block: mode == "block"}
}

// Name implements Analyzer.
func (a *ArtifactHashAnalyzer) Name() string { return "artifact-hash" }

// Analyze extracts candidate script paths from the command, resolves each
// against the working directory, and — for any that matches a manifest entry —
// verifies the on-disk content hash. Returns a finding only on a confirmed
// mismatch.
func (a *ArtifactHashAnalyzer) Analyze(ctx *AnalysisContext) []Finding {
	if a == nil || len(a.expected) == 0 || ctx.Cwd == "" {
		// No manifest, or no working directory to resolve relative paths
		// against (scan/check contexts) — nothing to verify.
		return nil
	}

	var findings []Finding
	seen := map[string]bool{} // avoid double-reporting the same file
	for _, cand := range a.candidatePaths(ctx) {
		abs := cand
		if !filepath.IsAbs(abs) {
			abs = filepath.Join(ctx.Cwd, abs)
		}
		abs = filepath.Clean(abs)
		if seen[abs] {
			continue
		}

		rel, declaredHash, ok := a.matchManifest(ctx.Cwd, abs)
		if !ok {
			continue
		}
		seen[abs] = true

		actual, err := sha256Hex(abs)
		if err != nil {
			// Can't read the file → can't confirm tampering. Skip (fail-safe).
			continue
		}
		if actual == declaredHash {
			continue // matches the reviewed baseline — allow
		}

		decision := "AUDIT"
		if a.block {
			decision = "BLOCK"
		}
		findings = append(findings, Finding{
			AnalyzerName: a.Name(),
			RuleID:       artifactRuleID,
			Decision:     decision,
			Confidence:   0.95,
			TaxonomyRef:  artifactTaxonomy,
			Tags:         []string{"supply-chain", "artifact-integrity", "skill"},
			Reason: "Skill bundled script '" + rel + "' does not match its declared integrity hash " +
				"(declared " + shortHash(declaredHash) + ", on disk " + shortHash(actual) + "). " +
				"An unreviewed script is executing under a reviewed skill's trust — the script was " +
				"modified after its manifest hash was recorded. Re-review and regenerate the skill's " +
				"declared baseline, or restore the approved script.",
		})
	}
	return findings
}

// candidatePaths gathers every path that could be the invoked script: the
// normalizer-extracted paths plus, belt-and-suspenders, the executable and
// args of each parsed segment (covers `./script`, `bash script`, `python -u
// script` regardless of how the normalizer treated them).
func (a *ArtifactHashAnalyzer) candidatePaths(ctx *AnalysisContext) []string {
	var out []string
	out = append(out, ctx.Paths...)
	if ctx.Parsed != nil {
		for _, seg := range allSegments(ctx.Parsed) {
			if looksLikePath(seg.Executable) {
				out = append(out, seg.Executable)
			}
			if seg.SubCommand != "" && looksLikePath(seg.SubCommand) {
				out = append(out, seg.SubCommand)
			}
			for _, arg := range seg.Args {
				if looksLikePath(arg) {
					out = append(out, arg)
				}
			}
		}
	}
	return out
}

// matchManifest returns the manifest path + declared hash for an absolute
// on-disk path, matching either an exact cwd-relative path or a repo-relative
// suffix (so the check still works when cwd is a subdirectory of the repo).
func (a *ArtifactHashAnalyzer) matchManifest(cwd, abs string) (rel, hash string, ok bool) {
	absSlash := filepath.ToSlash(abs)
	if r, err := filepath.Rel(cwd, abs); err == nil {
		rs := filepath.ToSlash(r)
		if h, found := a.expected[rs]; found {
			return rs, h, true
		}
	}
	for p, h := range a.expected {
		if absSlash == p || strings.HasSuffix(absSlash, "/"+p) {
			return p, h, true
		}
	}
	return "", "", false
}

// looksLikePath reports whether a token is plausibly a filesystem path to a
// script (has a path separator or a known script extension) and is not a flag.
func looksLikePath(tok string) bool {
	if tok == "" || strings.HasPrefix(tok, "-") {
		return false
	}
	if strings.Contains(tok, "/") {
		return true
	}
	switch strings.ToLower(filepath.Ext(tok)) {
	case ".sh", ".bash", ".py", ".js", ".mjs", ".cjs", ".ts", ".rb", ".pl", ".ps1":
		return true
	}
	return false
}

func sha256Hex(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}

func shortHash(h string) string {
	if len(h) <= 12 {
		return h
	}
	return h[:12] + "…"
}
