// Code generated by cmd/mcp-gen; DO NOT EDIT.
//
// This file is owned entirely by `cmd/mcp-gen`. Running `make mcp-gen` will
// fully rewrite both slices below. Do NOT add hand-curated scenarios here —
// they will be destroyed on the next generator run. Put hand-curated
// scenarios in curated_scenarios.go instead.
//
// The slices are intentionally empty scaffolding until the next `make mcp-gen`
// run repopulates GeneratedTPScenarios. Historical generator output that was
// committed prior to the split (issue #1174) has been migrated verbatim into
// curated_scenarios.go — see that file and the split commit for context.

package scenarios

// GeneratedTPScenarios are true-positive scenarios from shell-to-MCP rule conversion.
// Populated by cmd/mcp-gen. SAFE to regenerate in place.
var GeneratedTPScenarios = []Scenario{}

// GeneratedTNScenarios are true-negative scenarios from shell-to-MCP rule conversion.
// Populated by cmd/mcp-gen (currently unused — the generator emits only TPs).
// SAFE to regenerate in place.
var GeneratedTNScenarios = []Scenario{}
