// Curated MCP scenarios for issues #1758 and #1759.
// #1758: GitHub release creation and asset upload via MCP tools — supply chain gap.
// #1759: Screenshot tools called with no region argument — unscoped capture audit gap.
// Tests mcp-sc-block-github-release-create-named-tool,
//       mcp-sc-block-github-release-asset-upload-named-tool,
//       mcp-sc-block-github-releases-api-post,
//       mcp-computer-use-audit-unscoped-screenshot.

package scenarios

// GithubReleaseScreenshotScenarios contains TP and TN test scenarios for
// GitHub release creation/asset upload (supply chain) and unscoped screenshot (computer-use).
var GithubReleaseScreenshotScenarios = []Scenario{

	// ── mcp-sc-block-github-release-create-named-tool ────────────────────────

	{
		ID:               "MCP-TP-1758-001",
		ToolName:         "github_create_release",
		Arguments:        map[string]interface{}{"tag_name": "v1.0.0", "name": "Release v1.0.0", "body": "Release notes"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "github_create_release — must BLOCK (supply chain: unauthorized release creation)",
	},
	{
		ID:               "MCP-TP-1758-002",
		ToolName:         "create_release",
		Arguments:        map[string]interface{}{"tag": "v2.3.1", "draft": false},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "create_release — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-003",
		ToolName:         "publish_release",
		Arguments:        map[string]interface{}{"version": "1.5.0", "target_commitish": "main"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "publish_release — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-004",
		ToolName:         "gh_create_release",
		Arguments:        map[string]interface{}{"repo": "myorg/myapp", "tag": "v3.0.0"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "gh_create_release — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-005",
		ToolName:         "draft_release",
		Arguments:        map[string]interface{}{"tag": "v1.1.0-rc1", "title": "Release candidate"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "draft_release — must BLOCK",
	},
	{
		ID:               "MCP-TN-1758-001",
		ToolName:         "github_get_release",
		Arguments:        map[string]interface{}{"release_id": 12345},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "github_get_release (read-only) — must NOT block",
	},
	{
		ID:               "MCP-TN-1758-002",
		ToolName:         "list_releases",
		Arguments:        map[string]interface{}{"repo": "myorg/myapp"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-release-create-named-tool",
		Description:      "list_releases (read-only) — must NOT block",
	},

	// ── mcp-sc-block-github-release-asset-upload-named-tool ──────────────────

	{
		ID:               "MCP-TP-1758-006",
		ToolName:         "github_upload_release_asset",
		Arguments:        map[string]interface{}{"release_id": 123, "filename": "app-linux-amd64", "content_type": "application/octet-stream"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-asset-upload-named-tool",
		Description:      "github_upload_release_asset — must BLOCK (attaches malicious binary to release)",
	},
	{
		ID:               "MCP-TP-1758-007",
		ToolName:         "upload_release_asset",
		Arguments:        map[string]interface{}{"upload_url": "https://uploads.github.com/repos/org/repo/releases/123/assets", "name": "binary.tar.gz"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-asset-upload-named-tool",
		Description:      "upload_release_asset — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-008",
		ToolName:         "add_release_asset",
		Arguments:        map[string]interface{}{"release_id": 456, "asset_path": "./dist/app.zip"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-release-asset-upload-named-tool",
		Description:      "add_release_asset — must BLOCK",
	},
	{
		ID:               "MCP-TN-1758-003",
		ToolName:         "github_list_release_assets",
		Arguments:        map[string]interface{}{"release_id": 123},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-release-asset-upload-named-tool",
		Description:      "github_list_release_assets (read-only) — must NOT block",
	},
	{
		ID:               "MCP-TN-1758-004",
		ToolName:         "download_release_asset",
		Arguments:        map[string]interface{}{"asset_id": 789, "output_path": "./downloads/app.zip"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-release-asset-upload-named-tool",
		Description:      "download_release_asset (download, not upload) — must NOT block",
	},

	// ── mcp-sc-block-github-releases-api-post ────────────────────────────────

	{
		ID:               "MCP-TP-1758-009",
		ToolName:         "http_request",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/repo/releases", "method": "POST", "body": `{"tag_name":"v1.0.0"}`},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_request POST /repos/.../releases — must BLOCK (creates release via API)",
	},
	{
		ID:               "MCP-TP-1758-010",
		ToolName:         "http_post",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/myapp/releases"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_post to GitHub releases API — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-011",
		ToolName:         "http_request",
		Arguments:        map[string]interface{}{"url": "https://uploads.github.com/repos/org/myapp/releases/123/assets?name=binary", "method": "POST"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_request POST to uploads.github.com release assets — must BLOCK",
	},
	{
		ID:               "MCP-TP-1758-012",
		ToolName:         "api_request",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/repo/releases/456", "method": "PATCH"},
		ExpectedDecision: "BLOCK",
		Classification:   "TP",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "api_request PATCH to GitHub release — must BLOCK (modifies published release)",
	},
	{
		ID:               "MCP-TN-1758-005",
		ToolName:         "http_request",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/repo/releases", "method": "GET"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_request GET /releases (list releases, read-only) — must NOT block",
	},
	{
		ID:               "MCP-TN-1758-006",
		ToolName:         "http_request",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/repo/releases/123", "method": "GET"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_request GET single release (read-only) — must NOT block",
	},
	{
		ID:               "MCP-TN-1758-007",
		ToolName:         "http_get",
		Arguments:        map[string]interface{}{"url": "https://api.github.com/repos/org/repo/releases"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-sc-block-github-releases-api-post",
		Description:      "http_get releases list (read-only tool name) — must NOT block",
	},

	// ── mcp-computer-use-audit-unscoped-screenshot ────────────────────────────

	{
		ID:               "MCP-TP-1759-001",
		ToolName:         "take_screenshot",
		Arguments:        map[string]interface{}{},
		ExpectedDecision: "AUDIT",
		Classification:   "TP",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "take_screenshot with no args (unscoped, may capture full screen) — must AUDIT",
	},
	{
		ID:               "MCP-TP-1759-002",
		ToolName:         "capture_screen",
		Arguments:        map[string]interface{}{},
		ExpectedDecision: "AUDIT",
		Classification:   "TP",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "capture_screen with no args — must AUDIT",
	},
	{
		ID:               "MCP-TP-1759-003",
		ToolName:         "screenshot",
		Arguments:        map[string]interface{}{"format": "png"},
		ExpectedDecision: "AUDIT",
		Classification:   "TP",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "screenshot with format-only arg (no region, full-screen default) — must AUDIT",
	},
	{
		ID:               "MCP-TP-1759-004",
		ToolName:         "desktop_screenshot",
		Arguments:        map[string]interface{}{"filename": "screen.png"},
		ExpectedDecision: "AUDIT",
		Classification:   "TP",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "desktop_screenshot with filename-only arg (no region) — must AUDIT",
	},
	{
		ID:               "MCP-TN-1759-001",
		ToolName:         "take_screenshot",
		Arguments:        map[string]interface{}{"region": "application_window"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "take_screenshot with region=application_window (scoped) — must AUDIT only",
	},
	{
		ID:               "MCP-TN-1759-002",
		ToolName:         "capture_screen",
		Arguments:        map[string]interface{}{"region": "browser_only", "format": "jpeg"},
		ExpectedDecision: "AUDIT",
		Classification:   "TN",
		Category:         "mcp-computer-use-audit-unscoped-screenshot",
		Description:      "capture_screen with region=browser_only (scoped) — must AUDIT only",
	},
}
