#!/usr/bin/env bash
# check-fail-open-budget.sh — one number for the known fail-open residue
# (agentshield-oss #3995, step 3).
#
# Every parity sweep in internal/analyzer measures one evasion class against
# the BLOCKing corpus and tolerates a residue it names in a budget constant
# (`maxLeaks = 21`, `leakBudget := 3`, or a `{"<class>", <budget>, ...}` row
# in a per-position table). Twenty-five files, each honest on its own, and no
# place that says what they add up to — so the total could drift up one
# constant at a time and nobody would see a number move.
#
# This script reads those declarations out of the test sources and holds them
# against a committed baseline, scripts/fail-open-budget.txt:
#
#   - the TOTAL may not rise. A budget that goes UP is a fail-open decision
#     and it has to be visible in the diff of the baseline file, not buried in
#     a test constant.
#   - a new class is ADDED with its count (Gary, 2026-09-24: a newly found
#     shape goes on the budget, it is not fixed on sight — #3769's lesson).
#     Adding it means editing the baseline in the same PR, which is the point.
#   - a budget that goes DOWN also needs the baseline updated, so the file
#     stays the number CI reports rather than a stale upper bound.
#
# Source parsing, not runtime: the budgets are what the suite PERMITS, and the
# suite already fails when a measurement exceeds its budget. Reading the
# constants makes this check cost nothing and run everywhere `go test` does
# not (a docs-only CI lane, a laptop without the 40-minute analyzer suite).
# The limit of that choice: a parity test that expresses its tolerance some
# other way (an exact-rows table, a floor) is not a budget and is not counted.
#
# Exit: 0 baseline matches; 1 differs (the diff is printed); 2 nothing parsed.
#
# Usage:
#   scripts/check-fail-open-budget.sh            # verify
#   scripts/check-fail-open-budget.sh --update   # rewrite the baseline
#   scripts/check-fail-open-budget.sh --dir D --baseline F   # (tests)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="$REPO_ROOT/internal/analyzer"
BASELINE="$REPO_ROOT/scripts/fail-open-budget.txt"
UPDATE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --update)   UPDATE=1; shift ;;
    --dir)      DIR="$2"; shift 2 ;;
    --baseline) BASELINE="$2"; shift 2 ;;
    -h|--help)  sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "check-fail-open-budget: unknown argument: $1" >&2; exit 1 ;;
  esac
done

# collect prints "<file>:<class> <budget>" lines, one per declaration, in
# file order. Two shapes:
#   1. a named budget:  maxLeaks = 21 | maxLeaksEval = 40 | leakBudget := 3
#      The nth declaration of the same name in a file is suffixed #n, because
#      several sweeps set one budget for community packs and a second, higher
#      one when premium loads (`maxLeaks := 60` … `maxLeaks = 62`). Both are
#      tolerances the suite permits, so both count.
#   2. a table row in a file whose row struct has a `maxLeaks int` field:
#      {"exec-backslash", 3, 1900, 1200, ...} — class name first, budget
#      second.
collect() {
  local f base
  for f in "$DIR"/*parity*_test.go; do
    [ -f "$f" ] || continue
    base="$(basename "$f" _parity_test.go)"
    awk -v base="$base" '
      /^[[:space:]]*\/\// { next }
      {
        line = $0
        if (match(line, /(maxLeaks[A-Za-z0-9_]*|[A-Za-z0-9_]*[Ll]eakBudget[A-Za-z0-9_]*)[[:space:]]*(:=|=|:)[[:space:]]*[0-9]+/)) {
          decl = substr(line, RSTART, RLENGTH)
          name = decl; sub(/[[:space:]]*(:=|=|:).*/, "", name)
          val = decl; sub(/.*(:=|=|:)[[:space:]]*/, "", val)
          seen[name]++
          key = base ":" name
          if (seen[name] > 1) key = key "#" seen[name]
          print key " " val
          next
        }
        if (line ~ /maxLeaks[[:space:]]+int/) { table = 1; next }
        if (table && match(line, /^[[:space:]]*\{"[^"]+",[[:space:]]*[0-9]+,/)) {
          row = substr(line, RSTART, RLENGTH)
          cls = row; sub(/^[[:space:]]*\{"/, "", cls); sub(/".*/, "", cls)
          val = row; sub(/^[^,]*,[[:space:]]*/, "", val); sub(/,.*/, "", val)
          print base ":" cls " " val
        }
      }' "$f"
  done
}

CURRENT="$(collect)"
if [ -z "$CURRENT" ]; then
  echo "check-fail-open-budget: parsed 0 budget declarations under $DIR — vacuous, refusing to report a total of 0" >&2
  exit 2
fi
TOTAL=$(printf '%s\n' "$CURRENT" | awk '{s+=$2} END{print s+0}')
COUNT=$(printf '%s\n' "$CURRENT" | wc -l | tr -d ' ')

render() {
  printf '# Known fail-open residue permitted by the parity sweeps in internal/analyzer.\n'
  printf '# Generated by scripts/check-fail-open-budget.sh --update — do not edit by hand.\n'
  printf '# One line per budget declaration: <parity file>:<class> <budget>.\n'
  printf '# The TOTAL may only go down; a new class is added here with its count.\n'
  printf '%s\n' "$CURRENT"
  printf 'TOTAL %s\n' "$TOTAL"
}

if [ "$UPDATE" = "1" ]; then
  render > "$BASELINE"
  echo "check-fail-open-budget: wrote $BASELINE — $COUNT budgets, total $TOTAL"
  exit 0
fi

if [ ! -f "$BASELINE" ]; then
  echo "check-fail-open-budget: no baseline at $BASELINE — run with --update to create it (current total $TOTAL over $COUNT budgets)" >&2
  exit 1
fi

OLD_TOTAL=$(awk '/^TOTAL /{print $2}' "$BASELINE")
OLD_TOTAL=${OLD_TOTAL:-0}
OLD_ENTRIES="$(grep -vE '^(#|TOTAL )' "$BASELINE" | grep -v '^$' || true)"

if [ "$(printf '%s\n' "$OLD_ENTRIES")" = "$(printf '%s\n' "$CURRENT")" ] && [ "$OLD_TOTAL" = "$TOTAL" ]; then
  echo "check-fail-open-budget: OK — $COUNT budgets, total $TOTAL (unchanged)"
  exit 0
fi

echo "check-fail-open-budget: the budgets in internal/analyzer differ from $BASELINE"
if [ "$TOTAL" -gt "$OLD_TOTAL" ]; then
  echo "  ⛔ TOTAL ROSE: $OLD_TOTAL -> $TOTAL (+$((TOTAL-OLD_TOTAL))). A higher budget is a fail-open decision; it belongs in this diff, said out loud."
elif [ "$TOTAL" -lt "$OLD_TOTAL" ]; then
  echo "  ✅ total fell: $OLD_TOTAL -> $TOTAL (-$((OLD_TOTAL-TOTAL))). Ratchet it: rerun with --update and commit the baseline."
else
  echo "  total unchanged at $TOTAL, but the entries moved. Rerun with --update and commit the baseline."
fi
# Entry-level diff: added / removed / changed.
join -j1 -a1 -a2 -e MISSING -o '0,1.2,2.2' \
  <(printf '%s\n' "$OLD_ENTRIES" | sort) <(printf '%s\n' "$CURRENT" | sort) \
  | awk '$2 != $3 {
      if ($2 == "MISSING")      printf "  + %-60s %s   (new class — add it with its count)\n", $1, $3;
      else if ($3 == "MISSING") printf "  - %-60s %s   (removed)\n", $1, $2;
      else if ($3+0 > $2+0)     printf "  ^ %-60s %s -> %s   (UP)\n", $1, $2, $3;
      else                      printf "  v %-60s %s -> %s   (down)\n", $1, $2, $3;
    }'
exit 1
