package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// MCPGenRule is the output YAML structure matching MCPRule in policy.go.
type MCPGenRule struct {
	ID       string       `yaml:"id"`
	Taxonomy string       `yaml:"taxonomy,omitempty"`
	Match    MCPGenMatch  `yaml:"match"`
	Decision string       `yaml:"decision"`
	Reason   string       `yaml:"reason"`
}

// MCPGenMatch is the match block for generated rules.
type MCPGenMatch struct {
	ToolNameAny         []string            `yaml:"tool_name_any,omitempty"`
	ArgumentPatterns    map[string]string   `yaml:"argument_patterns,omitempty"`
	ArgumentPatternsAny map[string][]string `yaml:"argument_patterns_any,omitempty"`
}

// MCPGenPack is the full generated MCP pack.
type MCPGenPack struct {
	Name        string       `yaml:"name"`
	Description string       `yaml:"description"`
	Version     string       `yaml:"version"`
	Author      string       `yaml:"author"`
	Generated   string       `yaml:"generated"`
	Rules       []MCPGenRule `yaml:"rules"`
}

// EmitMCPPack merges candidates into the MCP pack YAML file at outPath.
//
// This MERGES rather than overwrites: any rule already present in the file
// on disk (by id) is kept verbatim in its existing on-disk order, and
// candidates are appended after it, skipping any candidate whose id already
// exists. A bare `go run ./cmd/mcp-gen` with no removal mechanism at all was
// the original #3367 bug — regeneration rewrote the file from just the
// current candidate set, so any id that fell out of classification (a
// classifier fix, a corpus change) silently vanished from a pack every
// community user's binary embeds. Rule removal is not something this tool
// does; that stays a human decision made by editing the YAML directly.
func EmitMCPPack(candidates []Candidate, outPath string) error {
	existing, err := loadMCPGenPack(outPath)
	if err != nil {
		return fmt.Errorf("read existing pack: %w", err)
	}

	existingIDs := make(map[string]bool, len(existing.Rules))
	for _, r := range existing.Rules {
		existingIDs[r.ID] = true
	}

	pack := MCPGenPack{
		Name:        "MCP Generated Rules (Shell-to-MCP)",
		Description: "Auto-generated MCP rules from convertible shell rules — credential files, config files, and sensitive paths",
		Version:     "1.0.0",
		Author:      "AgentShield MCP Generator",
		Generated:   time.Now().UTC().Format(time.RFC3339),
		Rules:       existing.Rules,
	}

	for _, c := range candidates {
		rule := candidateToRule(c)
		if existingIDs[rule.ID] {
			continue
		}
		pack.Rules = append(pack.Rules, rule)
		existingIDs[rule.ID] = true
	}

	data, err := yaml.Marshal(&pack)
	if err != nil {
		return fmt.Errorf("marshal YAML: %w", err)
	}

	// Add a header comment.
	header := "# Auto-generated by cmd/mcp-gen — do not edit manually.\n# Re-generate with: go run ./cmd/mcp-gen\n#\n# Source: shell rules from packs/*.yaml\n# Each rule protects a file path or URL that is equally reachable via MCP tool calls.\n\n"

	return os.WriteFile(outPath, []byte(header+string(data)), 0644)
}

// loadMCPGenPack reads an existing generated pack, if any. A missing file is
// not an error — it means this is the first-ever run — but a present,
// unparseable file is: silently treating it as empty would delete every rule
// it held the moment EmitMCPPack next writes out.
func loadMCPGenPack(path string) (MCPGenPack, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return MCPGenPack{}, nil
		}
		return MCPGenPack{}, err
	}
	var pack MCPGenPack
	if err := yaml.Unmarshal(data, &pack); err != nil {
		return MCPGenPack{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return pack, nil
}

// candidateToRule converts a Candidate into an MCPGenRule.
func candidateToRule(c Candidate) MCPGenRule {
	ruleID := candidateRuleID(c)
	match := MCPGenMatch{ToolNameAny: c.ToolNames}

	if c.Category == "url" {
		if len(c.URLs) > 0 {
			match.ArgumentPatterns = map[string]string{"url": "*" + c.URLs[0] + "*"}
		}
	} else if len(c.Paths) == 1 {
		match.ArgumentPatterns = map[string]string{"path": c.Paths[0]}
	} else if len(c.Paths) > 1 {
		// Multiple globs for one argument (e.g. anchored home-directory
		// variants from anchorToHomeDirs) are OR'd via argument_patterns_any —
		// picking only the first would silently drop coverage for the rest
		// (#3354: previously dropped 3 of 4 anchored home-dir variants).
		match.ArgumentPatternsAny = map[string][]string{"path": c.Paths}
	}

	reason := c.Reason
	if reason == "" {
		reason = fmt.Sprintf("Generated from shell rule %s — blocks MCP tool access to sensitive path.", c.SourceRule.ID)
	}

	taxonomy := c.SourceRule.Taxonomy
	if taxonomy == "" {
		taxonomy = "credential-exposure/config-file-access/mcp-generated"
	}

	return MCPGenRule{
		ID:       ruleID,
		Taxonomy: taxonomy,
		Match:    match,
		Decision: c.Decision,
		Reason:   fmt.Sprintf("[MCP] %s", strings.TrimPrefix(reason, "[MCP] ")),
	}
}
