package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// MCPGenRule is the output YAML structure matching MCPRule in policy.go.
type MCPGenRule struct {
	ID       string       `yaml:"id"`
	Taxonomy string       `yaml:"taxonomy,omitempty"`
	Match    MCPGenMatch  `yaml:"match"`
	Decision string       `yaml:"decision"`
	Reason   string       `yaml:"reason"`
}

// MCPGenMatch is the match block for generated rules.
type MCPGenMatch struct {
	ToolNameAny      []string          `yaml:"tool_name_any,omitempty"`
	ArgumentPatterns map[string]string `yaml:"argument_patterns,omitempty"`
}

// MCPGenPack is the full generated MCP pack.
type MCPGenPack struct {
	Name        string       `yaml:"name"`
	Description string       `yaml:"description"`
	Version     string       `yaml:"version"`
	Author      string       `yaml:"author"`
	Generated   string       `yaml:"generated"`
	Rules       []MCPGenRule `yaml:"rules"`
}

// EmitMCPPack converts candidates to an MCP pack YAML file.
func EmitMCPPack(candidates []Candidate, outPath string) error {
	pack := MCPGenPack{
		Name:        "MCP Generated Rules (Shell-to-MCP)",
		Description: "Auto-generated MCP rules from convertible shell rules — credential files, config files, and sensitive paths",
		Version:     "1.0.0",
		Author:      "AgentShield MCP Generator",
		Generated:   time.Now().UTC().Format(time.RFC3339),
	}

	for _, c := range candidates {
		rule := candidateToRule(c)
		pack.Rules = append(pack.Rules, rule)
	}

	data, err := yaml.Marshal(&pack)
	if err != nil {
		return fmt.Errorf("marshal YAML: %w", err)
	}

	// Add a header comment.
	header := "# Auto-generated by cmd/mcp-gen — do not edit manually.\n# Re-generate with: go run ./cmd/mcp-gen\n#\n# Source: shell rules from packs/*.yaml\n# Each rule protects a file path or URL that is equally reachable via MCP tool calls.\n\n"

	return os.WriteFile(outPath, []byte(header+string(data)), 0644)
}

// candidateToRule converts a Candidate into an MCPGenRule.
func candidateToRule(c Candidate) MCPGenRule {
	ruleID := candidateRuleID(c)
	argPatterns := map[string]string{}

	if c.Category == "url" {
		if len(c.URLs) == 1 {
			argPatterns["url"] = "*" + c.URLs[0] + "*"
		} else if len(c.URLs) > 1 {
			argPatterns["url"] = "*" + c.URLs[0] + "*"
		}
	} else {
		if len(c.Paths) == 1 {
			argPatterns["path"] = c.Paths[0]
		} else if len(c.Paths) > 1 {
			// Use the first path — each candidate should ideally have one path.
			argPatterns["path"] = c.Paths[0]
		}
	}

	reason := c.Reason
	if reason == "" {
		reason = fmt.Sprintf("Generated from shell rule %s — blocks MCP tool access to sensitive path.", c.SourceRule.ID)
	}

	taxonomy := c.SourceRule.Taxonomy
	if taxonomy == "" {
		taxonomy = "credential-exposure/config-file-access/mcp-generated"
	}

	return MCPGenRule{
		ID:       ruleID,
		Taxonomy: taxonomy,
		Match: MCPGenMatch{
			ToolNameAny:      c.ToolNames,
			ArgumentPatterns: argPatterns,
		},
		Decision: c.Decision,
		Reason:   fmt.Sprintf("[MCP] %s", strings.TrimPrefix(reason, "[MCP] ")),
	}
}
