package main

import (
	"fmt"
	"os"
	"strings"
)

// EmitScenarios generates a Go source file with TP scenarios for each candidate.
func EmitScenarios(candidates []Candidate, outPath string, startTPID, startTNID int) error {
	var buf strings.Builder

	buf.WriteString("// Code generated by cmd/mcp-gen; DO NOT EDIT.\n")
	buf.WriteString("package scenarios\n\n")
	buf.WriteString("// GeneratedTPScenarios are true-positive scenarios from shell-to-MCP rule conversion.\n")
	buf.WriteString("var GeneratedTPScenarios = []Scenario{\n")

	tpID := startTPID
	for _, c := range candidates {
		toolName := "read_file"
		if len(c.ToolNames) > 0 {
			toolName = c.ToolNames[0]
		}

		argKey := "path"
		argVal := "/etc/shadow" // fallback
		if c.Category == "url" && len(c.URLs) > 0 {
			argKey = "url"
			argVal = c.URLs[0]
			toolName = "http_request"
		} else if len(c.Paths) > 0 {
			argVal = exampleMaliciousPath(c.Paths[0])
		}

		// The policy engine uses most_restrictive_wins, so if an existing rule
		// blocks a broader category (e.g., system dir writes), the scenario will
		// see BLOCK even if this generated rule is AUDIT. Override AUDIT→BLOCK
		// only for paths in system directories where broader rules apply.
		expectedDecision := c.Decision
		if expectedDecision == "" {
			expectedDecision = "BLOCK"
		}
		if expectedDecision == "AUDIT" && isSystemPath(argVal) {
			expectedDecision = "BLOCK"
		}

		buf.WriteString("\t{\n")
		buf.WriteString(fmt.Sprintf("\t\tID:               \"MCP-TP-%03d\",\n", tpID))
		buf.WriteString(fmt.Sprintf("\t\tToolName:         %q,\n", toolName))
		buf.WriteString(fmt.Sprintf("\t\tArguments:        map[string]interface{}{%q: %q},\n", argKey, argVal))
		buf.WriteString(fmt.Sprintf("\t\tExpectedDecision: %q,\n", expectedDecision))
		buf.WriteString("\t\tClassification:   \"TP\",\n")
		buf.WriteString(fmt.Sprintf("\t\tCategory:         %q,\n", c.Category))
		buf.WriteString(fmt.Sprintf("\t\tDescription:      \"[Generated] %s\",\n", escapeGoString(shortDescription(c))))
		buf.WriteString("\t},\n")
		tpID++
	}

	buf.WriteString("}\n")

	return os.WriteFile(outPath, []byte(buf.String()), 0644)
}

// exampleMaliciousPath converts a glob pattern to a concrete malicious example path.
func exampleMaliciousPath(glob string) string {
	p := glob

	// For patterns like **/.ssh/config, produce /home/user/.ssh/config.
	if strings.HasPrefix(p, "**/") {
		p = "/home/user/" + strings.TrimPrefix(p, "**/")
	}

	// For patterns like /home/*/.aws/**, expand wildcards.
	p = strings.ReplaceAll(p, "/**", "/credentials")
	p = strings.ReplaceAll(p, "**", "")
	p = strings.ReplaceAll(p, "*", "user")

	// Clean up double slashes and trailing slashes.
	for strings.Contains(p, "//") {
		p = strings.ReplaceAll(p, "//", "/")
	}
	p = strings.TrimRight(p, "/")

	if !strings.HasPrefix(p, "/") {
		p = "/home/user/" + p
	}
	return p
}

// shortDescription creates a brief description for the scenario.
func shortDescription(c Candidate) string {
	if c.Category == "url" && len(c.URLs) > 0 {
		return fmt.Sprintf("MCP access to %s via %s", c.URLs[0], c.ToolNames[0])
	}
	if len(c.Paths) > 0 {
		return fmt.Sprintf("MCP access to %s", c.Paths[0])
	}
	return fmt.Sprintf("Generated from %s", c.SourceRule.ID)
}

// isSystemPath returns true if the path is in a system directory where broader
// MCP safety rules (mcp-safety pack) will BLOCK writes regardless of our rule.
func isSystemPath(path string) bool {
	systemPrefixes := []string{"/etc/", "/var/", "/usr/", "/opt/", "/root/", "/sys/", "/proc/"}
	for _, prefix := range systemPrefixes {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}

// escapeGoString escapes a string for use in Go source code.
func escapeGoString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}
